config/routes.rb
Rails.application.routes.draw do
 
  # * For Devise
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :kanban_boards

  resources :comments, only: [:edit, :update, :destroy]

  resources :other_boards, only: [:new, :create]

  # * Card resources set up this way to get to sort function. From Supe Rails youtube
  resources :cards do
    member do
      put :sort
    end
    resources :comments
  end

  # * Needed for the likes route
  put 'comment/:id/like', to: 'comments#like', as: 'like'
  delete 'comment/:id/like', to: 'comments#unlike', as: 'unlike'
  
  # * Column resources set up this way to get to sort function. From Supe Rails youtube
  resources :kanban_columns do
    member do
      put :sort
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ! root
  root to: 'kanban_boards#index'
end

app/models/kanban_board.rb
class KanbanBoard < ApplicationRecord
  validates :name, presence: true, on: :create
	belongs_to :user
  has_many :other_boards
  has_many :subscribers, through: :other_boards
  has_many :kanban_columns, dependent: :destroy
  # _destory is a special attribute that is used to mark a record for destruction
  accepts_nested_attributes_for :kanban_columns, reject_if: :all_blank, allow_destroy: true
end

app/controllers/kanban_boards_controller.rb
class KanbanBoardsController < ApplicationController
  def index
    @user = current_user
    @boards = @user.kanban_boards.all
  end

  def show
    @board = KanbanBoard.find(params[:id])
    @columns = @board.kanban_columns.all
    @board_id = params[:id]
  end

  # Upon creation the board will also allow columns to be built
  def new
    @board = KanbanBoard.new
    @board.kanban_columns.build
  end

  def create
    @board = KanbanBoard.new(kanban_board_params)
    
    respond_to do |format|
      if @board.save
        format.html { redirect_to kanban_board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @board = KanbanBoard.find(params[:id])
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to kanban_boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit
    @board = KanbanBoard.find(params[:id])
  end

  def update
    @board = KanbanBoard.find(params[:id])
    respond_to do |format|
      if @board.update(kanban_update_name_params)
        format.html { redirect_to kanban_board_url(@board.id), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def kanban_board_params
    params.require(:kanban_board).permit(:name, :user_id, kanban_columns_attributes: [:id, :name, :_destroy])  
  end

  def kanban_update_name_params
    params.require(:kanban_board).permit(:name)
  end

# class end
end

app/helpers/kanban_board_helper.rb
module KanbanBoardHelper
end

app/views/kanban_boards/_column_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label 'Column Name' %>
  <%= f.text_field :name, class:"form-control", style: 'width: 300px;' %>
  <button type="button" class="btn btn-warning mt-3" data-action="nested-form#remove">Remove Column</button>
  <%= f.hidden_field :_destroy %>
</div>

app/views/kanban_boards/_edit_form.html.erb
<%= form_with(model: board) do |f|%>
<div class="form-group">
  <h1>Board Name</h1>
  <%= f.text_field :name, class:"form-control", style:"width:300px" %>
  <%= f.submit 'Edit Name', class:"btn btn-primary mt-3"%>
</div>

<% end %>

app/views/kanban_boards/_form.html.erb
<%= form_with(model: board, data: {
  controller: "nested-form",
  nested_form_wrapper_selector_value: '.nested-form-wrapper'
  }) do |f| %>
  <%# Error message for board %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# This is where the board name is entered %>
  <div class="form-group">
    <%= f.label 'Board Name', style: "display: block" %>
    <%= f.text_field :name, class:"form-control", style: 'width: 300px;' %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>


  <%# Options for user to add columns %>
  <template data-nested-form-target="template">
    <%= f.fields_for :kanban_columns, KanbanColumn.new, child_index: 'NEW_RECORD' do |columns| %>
      <%= render "column_form", f: columns, board: board %>
    <% end %>
  </template>
  <%= f.fields_for :kanban_columns do |columns| %>
    <%= render "column_form", f: columns, board: board %>
  <% end %>

  <div data-nested-form-target="target"></div>
  <div class="d-flex justify-content-center">
    <button type="button" data-action="nested-form#add" class="btn btn-primary m-3">Add Column</button>
    <%# end of column addition %>
    <%# Create board button %>
    <%= f.submit 'Create!', class:"btn btn-primary m-3"%>
  </div>

<% end %>




  

app/views/kanban_boards/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <%= render "edit_form", board: @board %>
</body>
</html>

app/views/kanban_boards/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Page</title>
</head>
<body>
  <div class="container">
    <%= notice %>
    <div class="h-100 d-flex align-items-center justify-content-center">
      <div>
        <h1>Your Boards</h1>
        <div class="board-list">
          <% @boards.each do |board| %>
            <div class="board-container">
              <h2><%= link_to board.name, board %></h2>
            </div>
          <% end %>
        </div>
        <h1>Create a New Board</h1>
        <%= link_to 'Create Board', new_kanban_board_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/kanban_boards/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="d-flex justify-content-center">
    <h1>Create Board</h1>
  </div>
  <div class="d-flex justify-content-center">
    <%= render "form", board: @board %>
  </div>
</body>
</html>

app/views/kanban_boards/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Boards</title>
</head>
<body>
  <div style="color: green">
    <%= notice %>
  </div>

  <%# Kanban board %>
  <h1 class="h-100 d-flex align-items-center justify-content-center"><%= @board.name %></h1>

  <%# Columns and cards this uses the sortable javascript controller to sort the ul and li %>
  <div data-controller="sortable" data-sortable-group-value="column" class="h-100 d-flex align-items-center justify-content-center">
    <% @columns.rank(:row_order).each do | column | %>
      <ul data-sortable-update-url="<%= sort_kanban_column_path(column) %>">
        <div class="card mx-4">
          <div class="card-body bg-body-secondary">
            <li>
              <h3 class="fw-bold"><%=column.name %></h3>
            <ul data-controller="sortable" data-sortable-group-value="cards" data-sortable-column-id="<%=column.id%>">
            <% column.cards.rank(:row_order).each do |card| %>
              <li data-sortable-update-url="<%= sort_card_path(card) %>">
                <div class="card">
                  <div class="card-body">
                    <%= link_to "#{card.name}", card %>
                  </div>
                </div>
              </li>
              <% end %>
            </ul>
            </li>
          <%# Edit, create and delete links and buttons for column and cards %>
          <%= link_to "Create Card", new_card_path(:column => column.id), class:"btn btn-primary btn-sm mx-1" %>
          <%= link_to 'Edit Column', edit_kanban_column_path(column, :board => @board.id), class:"btn btn-info btn-sm mx-1"%>
          <%= button_to "Delete Column", kanban_column_path(column), method: :delete, class:"btn btn-danger btn-sm mt-2", data: { turbo_confirm: 'This will permanently delete the column. Are you sure?' } %>
          </div>
        </div>
      </ul>
    <% end %>
  </div>
  
  <br>
  <div class="h-100 d-flex align-items-center justify-content-center">
    <%# Edit, create and delete links and buttons for board and cards %>
    <%= link_to 'Add Column', new_kanban_column_path(:board => @board.id), class:"btn btn-secondary mx-3" %>
    <%= link_to "Edit Board", edit_kanban_board_path, class:"btn btn-info mx-3" %>
    <%= button_to "DELETE BOARD", @board, method: :delete, class:"btn btn-danger mx-3", data: { turbo_confirm: 'This will permanently delete the board. Are you sure?' } %>
  </div>

</body>
</html>