config/routes.rb
Rails.application.routes.draw do
 
  # * For Devise
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :kanban_boards

  resources :comments, only: [:edit, :update, :destroy]

  resources :other_boards, only: [:new, :create]

  # * Card resources set up this way to get to sort function. From Supe Rails youtube
  resources :cards do
    member do
      put :sort
    end
    resources :comments
  end

  # * Needed for the likes route
  put 'comment/:id/like', to: 'comments#like', as: 'like'
  delete 'comment/:id/like', to: 'comments#unlike', as: 'unlike'
  
  # * Column resources set up this way to get to sort function. From Supe Rails youtube
  resources :kanban_columns do
    member do
      put :sort
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ! root
  root to: 'kanban_boards#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true

  belongs_to :user
  belongs_to :card

  # * This is a self join for replies.
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  has_many :likes, dependent: :destroy

  def liked?(comment, user)
    array = []
    comment.likes.each do |like|
      array << like.user_id
    end
    if array.include?(user.id)
      true
    else
      false
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @card = Card.find(params[:card_id])
    @comment = @card.comments.new(parent_id: params[:parent_id])
    @parent_id = params[:parent_id]
  end

  def show
  end

  def create
    @card = Card.find(params[:card_id])
    @comment = Comment.new(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to card_path(@card), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @card = Card.find(@comment.card_id)
  end

  def update
    @comment = Comment.find(params[:id])
    @card = Card.find(@comment.card_id)

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to card_path(@card), notice: "Comment was successfully edited." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to card_path(@comment.card_id), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @comment = Comment.find(params[:comment_id])
    Like.create(user_id: current_user.id, comment_id: @comment.id)
    respond_to do |format|
      format.html { redirect_to card_path(@comment.card_id), notice: "Like was successfully created." }
      format.json { head :no_content }
    end
  end

  def unlike
    @comment = Comment.find(params[:comment_id])
    Like.destroy_by(user_id: current_user.id, comment_id: @comment.id)
    respond_to do |format|
      format.html { redirect_to card_path(@comment.card_id), notice: "Like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :card_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-3 p-3 bg-dark text-white border-light">
  <div class="card-body">
    <p><%= comment.comment %></p>
    
    <div class="mb-2">
      Likes: <%= comment.likes.count %>
    </div>
    
    <div class="d-flex mb-2">
      <% if comment.liked?(comment, current_user) %>
        <%= button_to 'Unlike', unlike_path(comment_id: comment.id), method: 'delete', class: 'btn btn-warning btn-sm me-2' %>
      <% else %>
        <%= button_to 'Like', like_path(comment_id: comment.id), method: 'put', class: 'btn btn-success btn-sm me-2' %>
      <% end %>

      <% if comment.user_id == current_user.id %>
        <%= link_to 'Edit Comment', edit_comment_path(comment), class: 'btn btn-info btn-sm me-2' %>
        <%= button_to 'Delete Comment', comment_path(comment), method: :delete, class: 'btn btn-danger btn-sm', data: { turbo_confirm: 'This will permanently delete the comment. Are you sure?' } %>
      <% end %>
    </div>
    
    <div data-controller="hide">
      <div hidden data-hide-target="reply">
        <%= render "comments/reply_form", card: Card.find(comment.card_id), parent_id: comment.id %>
      </div>
      <div class="d-flex mt-2">
        <button data-hide-target="button" data-action="hide#unhide" class="btn btn-secondary btn-sm me-2">Reply</button>
        <button hidden data-hide-target="discardbutton" data-action="hide#hide" class="btn btn-secondary btn-sm">Discard Reply</button>
      </div>
    </div>
    
    <% comment.replies.each do |reply| %>
      <div class="mt-3">
        <%= render "comments/comment", comment: reply %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [card, card.comments.build], local: true, class: 'mb-4' do |f| %>
  <div class="form-group">
    <%= f.label :comment, 'New Comment', class: 'form-label' %>
    <%= f.text_area :comment, class: 'form-control', rows: 3, style:'width:300px;' %>
  </div>
  
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :card_id, value: card.id %>
  
  <%= f.submit 'Comment', class: 'btn btn-primary mt-3' %>
<% end %>

app/views/comments/_reply_form.html.erb
<div class="border rounded p-3 mb-4 bg-dark text-white">
  <%= form_with(model: [card, card.comments.build], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :comment, 'New Comment', class: 'form-label' %>
      <%= f.text_area :comment, class: 'form-control', rows: 3 %>
    </div>
    
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :card_id, value: card.id %>
    <%= f.hidden_field :parent_id, value: parent_id %>
    
    <%= f.submit 'Reply', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Edit Comment</h1>
  <%= form_with model: @comment do |f| %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.text_area :comment, class:"form-control", style:"width:300px" %>
    </div>
      <%= f.hidden_field :user_id, :value => current_user.id%>
      <%= f.hidden_field :card_id, :value => @card.id%>
      <%= f.submit 'Edit', class:"btn btn-primary mt-3"%>
    </div>

<% end %>
</body>
</html>

app/views/comments/new.html.erb
# New is only for replies

<%= render 'reply_form', comment, parent_id %>