config/routes.rb
Rails.application.routes.draw do
 
  # * For Devise
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :kanban_boards

  resources :comments, only: [:edit, :update, :destroy]

  resources :other_boards, only: [:new, :create]

  # * Card resources set up this way to get to sort function. From Supe Rails youtube
  resources :cards do
    member do
      put :sort
    end
    resources :comments
  end

  # * Needed for the likes route
  put 'comment/:id/like', to: 'comments#like', as: 'like'
  delete 'comment/:id/like', to: 'comments#unlike', as: 'unlike'
  
  # * Column resources set up this way to get to sort function. From Supe Rails youtube
  resources :kanban_columns do
    member do
      put :sort
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ! root
  root to: 'kanban_boards#index'
end

app/models/card.rb
class Card < ApplicationRecord
  # ! validations
  validates :name, presence: true, on: :create
  validates :kanban_column_id, presence: true, on: :create


  belongs_to :kanban_column
  has_many :comments, dependent: :destroy

  # * from the ranked model gem https://github.com/brendon/ranked-model needed for sorting cards and columns
  include RankedModel
  ranks :row_order, with_same: :kanban_column_id

  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
	def sort
		@card = Card.find(params[:id])
		@card.update(row_order_position: params[:row_order_position], kanban_column_id: params[:column_id])
		head :no_content
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	
  def new
    @card = Card.new
    @column_id = params[:column]
  end
  
  def show
    @card = Card.find(params[:id])
    column = KanbanColumn.find(@card.kanban_column_id)
    @board = KanbanBoard.find(column.kanban_board_id)
  end

  def edit
    @card = Card.find(params[:id])
  end
  
  # this is needed to store data for the sortable javascript controller
  def sort
		@card = Card.find(params[:id])
		@card.update(row_order_position: params[:row_order_position], kanban_column_id: params[:column_id])
		head :no_content
  end

  def create
    @card = Card.new(new_card_params)
    column_id = @card.kanban_column_id
    column = KanbanColumn.find(column_id)
    board = KanbanBoard.find(column.kanban_board_id)
    
    respond_to do |format|
      if @card.save
        format.html { redirect_to kanban_board_path(board), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @card = Card.find(params[:id])
    column_id = @card.kanban_column_id
    column = KanbanColumn.find(column_id)
    board = KanbanBoard.find(column.kanban_board_id)
    respond_to do |format|
      if @card.update(update_card_params)
        format.html { redirect_to kanban_board_path(board), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card = Card.find(params[:id])
    column_id = @card.kanban_column_id
    column = KanbanColumn.find(column_id)
    board = KanbanBoard.find(column.kanban_board_id)
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to kanban_board_path(board), notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def new_card_params
    params.require(:card).permit(:name, :description, :start_date, :due_date, :kanban_column_id)
  end

  def update_card_params
    params.require(:card).permit(:name, :description, :start_date, :due_date)
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "card-form") do |form| %>
  <% if card.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>
      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label 'Name' %>
    <%= form.text_field :name, class: 'form-control', style: 'width: 300px;' %>
  </div>

  <div class="form-group">
    <%= form.label 'Description' %>
    <%= form.text_area :description, class: 'form-control', style: 'width: 300px;' %>
  </div>
  
  <div class="form-group">
    <%= form.label 'Start' %>
    <%= form.date_field :start_date, class: 'form-control', style: 'width: 300px;' %>
  </div>
  
  <div class="form-group">
    <%= form.label 'Due' %>
    <%= form.date_field :due_date, class: 'form-control', style: 'width: 300px;' %>
  </div>
  
  <%= form.hidden_field :kanban_column_id, value: @column_id %>
  
  <div class="form-group mt-3"> <!-- Added mt-3 for margin-top -->
    <%= form.submit 'Create Card', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Card</title>
</head>
<body>
  <%= form_with(model: @card) do |form| %>
    <% if @card.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
        <ul>
          <% @card.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h3>Edit Card</h3>
    <div class="form-group">
      <%= form.label 'Name', style: "display: block" %>
      <%= form.text_field :name, class:"form-control", style:"width:300px" %>
      <%= form.label 'Description', style: "display: block" %>
      <%= form.text_area :description, class:"form-control", style:"width:300px" %>
      <%= form.label 'Start', style: "display: block" %>
      <%= form.date_field :start_date %>
      <%= form.label 'Due', style: "display: block" %>
      <%= form.date_field :due_date %>
      <div class="form-group">
        <%= form.submit 'Edit Card', class:"btn btn-primary mt-3" %>
      </div>
    </div>


  <% end %>
  
</body>
</html>

app/views/cards/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Card</title>
</head>
<body>
  <div class="d-flex justify-content-center">
    <h1>Create Card</h1>
  </div>
  <div class="d-flex justify-content-center">
    <%= render "form", card: @card %>
  </div>
</body>
</html>

app/views/cards/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%=@card.name%></title>
</head>
<body>
  <h3><%= notice %></h3>
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h1 class="card-title">Card Info</h1>
    </div>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <strong>Card Name:</strong> <%= @card.name %>
        </li>
        <li class="list-group-item">
          <strong>Description:</strong> <%= @card.description %>
        </li>
        <li class="list-group-item">
          <strong>Start Date:</strong> <%= @card.start_date.present? ? @card.start_date.strftime("%B %d, %Y") : 'Not set' %>
        </li>
        <li class="list-group-item">
          <strong>Due Date:</strong> <%= @card.due_date.present? ? @card.due_date.strftime("%B %d, %Y") : 'Not set' %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <%# To create comments %>
  <%= render 'comments/form', card: @card %>

  <%# view comments %>
  <% @card.comments.each do |comment| %>
    <%# this if statement prevents an extra blank comment from being generated %>
    <% if comment.comment.blank? %>
    <% elsif comment.parent_id.blank?%>
      <%= render 'comments/comment', comment: comment, :card => @card %>
    <% end %>
  <% end %>

  <%# links and buttoms %>
  <%= link_to 'Edit Card', edit_card_path %>
  <%= link_to 'Back to board', kanban_board_path(@board)%>
  <%= button_to "DELETE CARD", @card, method: :delete, class: 'btn btn-danger' ,form: { data: { turbo_confirm: 'This will permanently delete the card. Are you sure?' } } %>
</div>


</body>
</html>